# Microsoft Developer Studio Generated NMAKE File, Based on megatune.dsp
!IF "$(CFG)" == ""
CFG=megatune - Win32 Debug
!MESSAGE No configuration specified. Defaulting to megatune - Win32 Debug.
!ENDIF 

!MESSAGE $(CFG)

!IF "$(CFG)" != "megatune - Win32 Release" && "$(CFG)" != "megatune - Win32 Debug"
!MESSAGE Invalid configuration "$(CFG)" specified.
!MESSAGE You can specify a configuration when running NMAKE
!MESSAGE by defining the macro CFG on the command line. For example:
!MESSAGE 
!MESSAGE NMAKE /f "megatune.mak" CFG="megatune - Win32 Debug"
!MESSAGE 
!MESSAGE Possible choices for configuration are:
!MESSAGE 
!MESSAGE "megatune - Win32 Release" (based on "Win32 (x86) Application")
!MESSAGE "megatune - Win32 Debug" (based on "Win32 (x86) Application")
!MESSAGE 
!ERROR An invalid configuration is specified.
!ENDIF 

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE 
NULL=nul
!ENDIF 

!IF  "$(CFG)" == "megatune - Win32 Release"

OUTDIR=.\Release
INTDIR=.\Release
# Begin Custom Macros
OutDir=.\Release
# End Custom Macros

ALL : "$(OUTDIR)\megatune.exe" "$(OUTDIR)\Megatune.tlb" ".\Megatune_i.h" ".\Megatune_i.c" "$(OUTDIR)\megatune.bsc"


CLEAN :
	-@erase "$(INTDIR)\aeWizard.obj"
	-@erase "$(INTDIR)\aeWizard.sbr"
	-@erase "$(INTDIR)\AnalogMeter.obj"
	-@erase "$(INTDIR)\AnalogMeter.sbr"
	-@erase "$(INTDIR)\Application.obj"
	-@erase "$(INTDIR)\Application.sbr"
	-@erase "$(INTDIR)\BarMeter.obj"
	-@erase "$(INTDIR)\BarMeter.sbr"
	-@erase "$(INTDIR)\burstLog.obj"
	-@erase "$(INTDIR)\burstLog.sbr"
	-@erase "$(INTDIR)\byteString.obj"
	-@erase "$(INTDIR)\byteString.sbr"
	-@erase "$(INTDIR)\COMSymbol.obj"
	-@erase "$(INTDIR)\COMSymbol.sbr"
	-@erase "$(INTDIR)\controller.obj"
	-@erase "$(INTDIR)\controller.sbr"
	-@erase "$(INTDIR)\curveEditor.obj"
	-@erase "$(INTDIR)\curveEditor.sbr"
	-@erase "$(INTDIR)\Dabout.obj"
	-@erase "$(INTDIR)\Dabout.sbr"
	-@erase "$(INTDIR)\dataDialog.obj"
	-@erase "$(INTDIR)\dataDialog.sbr"
	-@erase "$(INTDIR)\datalog.obj"
	-@erase "$(INTDIR)\datalog.sbr"
	-@erase "$(INTDIR)\Dconplot.obj"
	-@erase "$(INTDIR)\Dconplot.sbr"
	-@erase "$(INTDIR)\Dconstants.obj"
	-@erase "$(INTDIR)\Dconstants.sbr"
	-@erase "$(INTDIR)\Denrichments.obj"
	-@erase "$(INTDIR)\Denrichments.sbr"
	-@erase "$(INTDIR)\dirSelect.obj"
	-@erase "$(INTDIR)\dirSelect.sbr"
	-@erase "$(INTDIR)\DlogOptions.obj"
	-@erase "$(INTDIR)\DlogOptions.sbr"
	-@erase "$(INTDIR)\Dreqfuel.obj"
	-@erase "$(INTDIR)\Dreqfuel.sbr"
	-@erase "$(INTDIR)\Druntime.obj"
	-@erase "$(INTDIR)\Druntime.sbr"
	-@erase "$(INTDIR)\Dsetcomm.obj"
	-@erase "$(INTDIR)\Dsetcomm.sbr"
	-@erase "$(INTDIR)\tuning3D.obj"
	-@erase "$(INTDIR)\tuning3D.sbr"
	-@erase "$(INTDIR)\DveGen.obj"
	-@erase "$(INTDIR)\DveGen.sbr"
	-@erase "$(INTDIR)\gaugeConfig.obj"
	-@erase "$(INTDIR)\gaugeConfig.sbr"
	-@erase "$(INTDIR)\genO2.obj"
	-@erase "$(INTDIR)\genO2.sbr"
	-@erase "$(INTDIR)\genTherm.obj"
	-@erase "$(INTDIR)\genTherm.sbr"
	-@erase "$(INTDIR)\hexedit.obj"
	-@erase "$(INTDIR)\hexedit.sbr"
	-@erase "$(INTDIR)\injControl.obj"
	-@erase "$(INTDIR)\injControl.sbr"
	-@erase "$(INTDIR)\injectorSize.obj"
	-@erase "$(INTDIR)\injectorSize.sbr"
	-@erase "$(INTDIR)\megatune.obj"
	-@erase "$(INTDIR)\megatune.pch"
	-@erase "$(INTDIR)\megatune.res"
	-@erase "$(INTDIR)\megatune.sbr"
	-@erase "$(INTDIR)\Megatune.tlb"
	-@erase "$(INTDIR)\megatuneDlg.obj"
	-@erase "$(INTDIR)\megatuneDlg.sbr"
	-@erase "$(INTDIR)\miniDOM.obj"
	-@erase "$(INTDIR)\miniDOM.sbr"
	-@erase "$(INTDIR)\miniTerm.obj"
	-@erase "$(INTDIR)\miniTerm.sbr"
	-@erase "$(INTDIR)\msComm.obj"
	-@erase "$(INTDIR)\msComm.sbr"
	-@erase "$(INTDIR)\msDatabase.obj"
	-@erase "$(INTDIR)\msDatabase.sbr"
	-@erase "$(INTDIR)\msqInfoDlg.obj"
	-@erase "$(INTDIR)\msqInfoDlg.sbr"
	-@erase "$(INTDIR)\parser.obj"
	-@erase "$(INTDIR)\parser.sbr"
	-@erase "$(INTDIR)\plot3d.obj"
	-@erase "$(INTDIR)\plot3d.sbr"
	-@erase "$(INTDIR)\portEdit.obj"
	-@erase "$(INTDIR)\portEdit.sbr"
	-@erase "$(INTDIR)\repository.obj"
	-@erase "$(INTDIR)\repository.sbr"
	-@erase "$(INTDIR)\scaleVe.obj"
	-@erase "$(INTDIR)\scaleVe.sbr"
	-@erase "$(INTDIR)\selectList.obj"
	-@erase "$(INTDIR)\selectList.sbr"
	-@erase "$(INTDIR)\Splash.obj"
	-@erase "$(INTDIR)\Splash.sbr"
	-@erase "$(INTDIR)\StdAfx.obj"
	-@erase "$(INTDIR)\StdAfx.sbr"
	-@erase "$(INTDIR)\symbol.obj"
	-@erase "$(INTDIR)\symbol.sbr"
	-@erase "$(INTDIR)\tableEditor.obj"
	-@erase "$(INTDIR)\tableEditor.sbr"
	-@erase "$(INTDIR)\tokenizer.obj"
	-@erase "$(INTDIR)\tokenizer.sbr"
	-@erase "$(INTDIR)\tpgen.obj"
	-@erase "$(INTDIR)\tpgen.sbr"
	-@erase "$(INTDIR)\transformTable.obj"
	-@erase "$(INTDIR)\transformTable.sbr"
	-@erase "$(INTDIR)\triggerWizard.obj"
	-@erase "$(INTDIR)\triggerWizard.sbr"
	-@erase "$(INTDIR)\units.obj"
	-@erase "$(INTDIR)\units.sbr"
	-@erase "$(INTDIR)\userDefined.obj"
	-@erase "$(INTDIR)\userDefined.sbr"
	-@erase "$(INTDIR)\userHelp.obj"
	-@erase "$(INTDIR)\userHelp.sbr"
	-@erase "$(INTDIR)\userMenu.obj"
	-@erase "$(INTDIR)\userMenu.sbr"
	-@erase "$(INTDIR)\vc60.idb"
	-@erase "$(INTDIR)\vegen.obj"
	-@erase "$(INTDIR)\vegen.sbr"
	-@erase "$(INTDIR)\Vex.obj"
	-@erase "$(INTDIR)\Vex.sbr"
	-@erase "$(INTDIR)\wueWizard.obj"
	-@erase "$(INTDIR)\wueWizard.sbr"
	-@erase "$(OUTDIR)\megatune.bsc"
	-@erase "$(OUTDIR)\megatune.exe"

"$(OUTDIR)" :
    if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

F90=df.exe
CPP=cl.exe
CPP_PROJ=/nologo /MT /W3 /GR /GX /O2 /D "WIN32" /D "NDEBUG" /D "_WINDOWS" /FR"$(INTDIR)\\" /Fp"$(INTDIR)\megatune.pch" /Yu"stdafx.h" /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c 

.c{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.c{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

MTL=midl.exe
MTL_PROJ=/nologo /D "NDEBUG" /mktyplib203 /o "NUL" /win32 
RSC=rc.exe
RSC_PROJ=/l 0x409 /fo"$(INTDIR)\megatune.res" /d "NDEBUG" 
BSC32=bscmake.exe
BSC32_FLAGS=/o"$(OUTDIR)\megatune.bsc" 
BSC32_SBRS= \
	"$(INTDIR)\aeWizard.sbr" \
	"$(INTDIR)\AnalogMeter.sbr" \
	"$(INTDIR)\Application.sbr" \
	"$(INTDIR)\BarMeter.sbr" \
	"$(INTDIR)\burstLog.sbr" \
	"$(INTDIR)\byteString.sbr" \
	"$(INTDIR)\COMSymbol.sbr" \
	"$(INTDIR)\controller.sbr" \
	"$(INTDIR)\curveEditor.sbr" \
	"$(INTDIR)\Dabout.sbr" \
	"$(INTDIR)\dataDialog.sbr" \
	"$(INTDIR)\datalog.sbr" \
	"$(INTDIR)\Dconplot.sbr" \
	"$(INTDIR)\Dconstants.sbr" \
	"$(INTDIR)\Denrichments.sbr" \
	"$(INTDIR)\dirSelect.sbr" \
	"$(INTDIR)\DlogOptions.sbr" \
	"$(INTDIR)\Dreqfuel.sbr" \
	"$(INTDIR)\Druntime.sbr" \
	"$(INTDIR)\Dsetcomm.sbr" \
	"$(INTDIR)\tuning3D.sbr" \
	"$(INTDIR)\DveGen.sbr" \
	"$(INTDIR)\gaugeConfig.sbr" \
	"$(INTDIR)\genO2.sbr" \
	"$(INTDIR)\genTherm.sbr" \
	"$(INTDIR)\hexedit.sbr" \
	"$(INTDIR)\injControl.sbr" \
	"$(INTDIR)\injectorSize.sbr" \
	"$(INTDIR)\megatune.sbr" \
	"$(INTDIR)\megatuneDlg.sbr" \
	"$(INTDIR)\miniDOM.sbr" \
	"$(INTDIR)\miniTerm.sbr" \
	"$(INTDIR)\msComm.sbr" \
	"$(INTDIR)\msDatabase.sbr" \
	"$(INTDIR)\msqInfoDlg.sbr" \
	"$(INTDIR)\parser.sbr" \
	"$(INTDIR)\plot3d.sbr" \
	"$(INTDIR)\portEdit.sbr" \
	"$(INTDIR)\repository.sbr" \
	"$(INTDIR)\scaleVe.sbr" \
	"$(INTDIR)\selectList.sbr" \
	"$(INTDIR)\Splash.sbr" \
	"$(INTDIR)\StdAfx.sbr" \
	"$(INTDIR)\symbol.sbr" \
	"$(INTDIR)\tableEditor.sbr" \
	"$(INTDIR)\tokenizer.sbr" \
	"$(INTDIR)\tpgen.sbr" \
	"$(INTDIR)\transformTable.sbr" \
	"$(INTDIR)\triggerWizard.sbr" \
	"$(INTDIR)\units.sbr" \
	"$(INTDIR)\userDefined.sbr" \
	"$(INTDIR)\userHelp.sbr" \
	"$(INTDIR)\userMenu.sbr" \
	"$(INTDIR)\vegen.sbr" \
	"$(INTDIR)\Vex.sbr" \
	"$(INTDIR)\wueWizard.sbr"

"$(OUTDIR)\megatune.bsc" : "$(OUTDIR)" $(BSC32_SBRS)
    $(BSC32) @<<
  $(BSC32_FLAGS) $(BSC32_SBRS)
<<

LINK32=link.exe
LINK32_FLAGS=winmm.lib /nologo /subsystem:windows /incremental:no /pdb:"$(OUTDIR)\megatune.pdb" /machine:I386 /out:"$(OUTDIR)\megatune.exe" 
LINK32_OBJS= \
	"$(INTDIR)\aeWizard.obj" \
	"$(INTDIR)\AnalogMeter.obj" \
	"$(INTDIR)\Application.obj" \
	"$(INTDIR)\BarMeter.obj" \
	"$(INTDIR)\burstLog.obj" \
	"$(INTDIR)\byteString.obj" \
	"$(INTDIR)\COMSymbol.obj" \
	"$(INTDIR)\controller.obj" \
	"$(INTDIR)\curveEditor.obj" \
	"$(INTDIR)\Dabout.obj" \
	"$(INTDIR)\dataDialog.obj" \
	"$(INTDIR)\datalog.obj" \
	"$(INTDIR)\Dconplot.obj" \
	"$(INTDIR)\Dconstants.obj" \
	"$(INTDIR)\Denrichments.obj" \
	"$(INTDIR)\dirSelect.obj" \
	"$(INTDIR)\DlogOptions.obj" \
	"$(INTDIR)\Dreqfuel.obj" \
	"$(INTDIR)\Druntime.obj" \
	"$(INTDIR)\Dsetcomm.obj" \
	"$(INTDIR)\tuning3D.obj" \
	"$(INTDIR)\DveGen.obj" \
	"$(INTDIR)\gaugeConfig.obj" \
	"$(INTDIR)\genO2.obj" \
	"$(INTDIR)\genTherm.obj" \
	"$(INTDIR)\hexedit.obj" \
	"$(INTDIR)\injControl.obj" \
	"$(INTDIR)\injectorSize.obj" \
	"$(INTDIR)\megatune.obj" \
	"$(INTDIR)\megatuneDlg.obj" \
	"$(INTDIR)\miniDOM.obj" \
	"$(INTDIR)\miniTerm.obj" \
	"$(INTDIR)\msComm.obj" \
	"$(INTDIR)\msDatabase.obj" \
	"$(INTDIR)\msqInfoDlg.obj" \
	"$(INTDIR)\parser.obj" \
	"$(INTDIR)\plot3d.obj" \
	"$(INTDIR)\portEdit.obj" \
	"$(INTDIR)\repository.obj" \
	"$(INTDIR)\scaleVe.obj" \
	"$(INTDIR)\selectList.obj" \
	"$(INTDIR)\Splash.obj" \
	"$(INTDIR)\StdAfx.obj" \
	"$(INTDIR)\symbol.obj" \
	"$(INTDIR)\tableEditor.obj" \
	"$(INTDIR)\tokenizer.obj" \
	"$(INTDIR)\tpgen.obj" \
	"$(INTDIR)\transformTable.obj" \
	"$(INTDIR)\triggerWizard.obj" \
	"$(INTDIR)\units.obj" \
	"$(INTDIR)\userDefined.obj" \
	"$(INTDIR)\userHelp.obj" \
	"$(INTDIR)\userMenu.obj" \
	"$(INTDIR)\vegen.obj" \
	"$(INTDIR)\Vex.obj" \
	"$(INTDIR)\wueWizard.obj" \
	"$(INTDIR)\megatune.res"

"$(OUTDIR)\megatune.exe" : "$(OUTDIR)" $(DEF_FILE) $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

!ELSEIF  "$(CFG)" == "megatune - Win32 Debug"

OUTDIR=.\Debug
INTDIR=.\Debug
# Begin Custom Macros
OutDir=.\Debug
# End Custom Macros

ALL : "$(OUTDIR)\megatune.exe" "$(OUTDIR)\Megatune.tlb" ".\Megatune_i.h" ".\Megatune_i.c" "$(OUTDIR)\megatune.bsc"


CLEAN :
	-@erase "$(INTDIR)\aeWizard.obj"
	-@erase "$(INTDIR)\aeWizard.sbr"
	-@erase "$(INTDIR)\AnalogMeter.obj"
	-@erase "$(INTDIR)\AnalogMeter.sbr"
	-@erase "$(INTDIR)\Application.obj"
	-@erase "$(INTDIR)\Application.sbr"
	-@erase "$(INTDIR)\BarMeter.obj"
	-@erase "$(INTDIR)\BarMeter.sbr"
	-@erase "$(INTDIR)\burstLog.obj"
	-@erase "$(INTDIR)\burstLog.sbr"
	-@erase "$(INTDIR)\byteString.obj"
	-@erase "$(INTDIR)\byteString.sbr"
	-@erase "$(INTDIR)\COMSymbol.obj"
	-@erase "$(INTDIR)\COMSymbol.sbr"
	-@erase "$(INTDIR)\controller.obj"
	-@erase "$(INTDIR)\controller.sbr"
	-@erase "$(INTDIR)\curveEditor.obj"
	-@erase "$(INTDIR)\curveEditor.sbr"
	-@erase "$(INTDIR)\Dabout.obj"
	-@erase "$(INTDIR)\Dabout.sbr"
	-@erase "$(INTDIR)\dataDialog.obj"
	-@erase "$(INTDIR)\dataDialog.sbr"
	-@erase "$(INTDIR)\datalog.obj"
	-@erase "$(INTDIR)\datalog.sbr"
	-@erase "$(INTDIR)\Dconplot.obj"
	-@erase "$(INTDIR)\Dconplot.sbr"
	-@erase "$(INTDIR)\Dconstants.obj"
	-@erase "$(INTDIR)\Dconstants.sbr"
	-@erase "$(INTDIR)\Denrichments.obj"
	-@erase "$(INTDIR)\Denrichments.sbr"
	-@erase "$(INTDIR)\dirSelect.obj"
	-@erase "$(INTDIR)\dirSelect.sbr"
	-@erase "$(INTDIR)\DlogOptions.obj"
	-@erase "$(INTDIR)\DlogOptions.sbr"
	-@erase "$(INTDIR)\Dreqfuel.obj"
	-@erase "$(INTDIR)\Dreqfuel.sbr"
	-@erase "$(INTDIR)\Druntime.obj"
	-@erase "$(INTDIR)\Druntime.sbr"
	-@erase "$(INTDIR)\Dsetcomm.obj"
	-@erase "$(INTDIR)\Dsetcomm.sbr"
	-@erase "$(INTDIR)\tuning3D.obj"
	-@erase "$(INTDIR)\tuning3D.sbr"
	-@erase "$(INTDIR)\DveGen.obj"
	-@erase "$(INTDIR)\DveGen.sbr"
	-@erase "$(INTDIR)\gaugeConfig.obj"
	-@erase "$(INTDIR)\gaugeConfig.sbr"
	-@erase "$(INTDIR)\genO2.obj"
	-@erase "$(INTDIR)\genO2.sbr"
	-@erase "$(INTDIR)\genTherm.obj"
	-@erase "$(INTDIR)\genTherm.sbr"
	-@erase "$(INTDIR)\hexedit.obj"
	-@erase "$(INTDIR)\hexedit.sbr"
	-@erase "$(INTDIR)\injControl.obj"
	-@erase "$(INTDIR)\injControl.sbr"
	-@erase "$(INTDIR)\injectorSize.obj"
	-@erase "$(INTDIR)\injectorSize.sbr"
	-@erase "$(INTDIR)\megatune.obj"
	-@erase "$(INTDIR)\megatune.pch"
	-@erase "$(INTDIR)\megatune.res"
	-@erase "$(INTDIR)\megatune.sbr"
	-@erase "$(INTDIR)\Megatune.tlb"
	-@erase "$(INTDIR)\megatuneDlg.obj"
	-@erase "$(INTDIR)\megatuneDlg.sbr"
	-@erase "$(INTDIR)\miniDOM.obj"
	-@erase "$(INTDIR)\miniDOM.sbr"
	-@erase "$(INTDIR)\miniTerm.obj"
	-@erase "$(INTDIR)\miniTerm.sbr"
	-@erase "$(INTDIR)\msComm.obj"
	-@erase "$(INTDIR)\msComm.sbr"
	-@erase "$(INTDIR)\msDatabase.obj"
	-@erase "$(INTDIR)\msDatabase.sbr"
	-@erase "$(INTDIR)\msqInfoDlg.obj"
	-@erase "$(INTDIR)\msqInfoDlg.sbr"
	-@erase "$(INTDIR)\parser.obj"
	-@erase "$(INTDIR)\parser.sbr"
	-@erase "$(INTDIR)\plot3d.obj"
	-@erase "$(INTDIR)\plot3d.sbr"
	-@erase "$(INTDIR)\portEdit.obj"
	-@erase "$(INTDIR)\portEdit.sbr"
	-@erase "$(INTDIR)\repository.obj"
	-@erase "$(INTDIR)\repository.sbr"
	-@erase "$(INTDIR)\scaleVe.obj"
	-@erase "$(INTDIR)\scaleVe.sbr"
	-@erase "$(INTDIR)\selectList.obj"
	-@erase "$(INTDIR)\selectList.sbr"
	-@erase "$(INTDIR)\Splash.obj"
	-@erase "$(INTDIR)\Splash.sbr"
	-@erase "$(INTDIR)\StdAfx.obj"
	-@erase "$(INTDIR)\StdAfx.sbr"
	-@erase "$(INTDIR)\symbol.obj"
	-@erase "$(INTDIR)\symbol.sbr"
	-@erase "$(INTDIR)\tableEditor.obj"
	-@erase "$(INTDIR)\tableEditor.sbr"
	-@erase "$(INTDIR)\tokenizer.obj"
	-@erase "$(INTDIR)\tokenizer.sbr"
	-@erase "$(INTDIR)\tpgen.obj"
	-@erase "$(INTDIR)\tpgen.sbr"
	-@erase "$(INTDIR)\transformTable.obj"
	-@erase "$(INTDIR)\transformTable.sbr"
	-@erase "$(INTDIR)\triggerWizard.obj"
	-@erase "$(INTDIR)\triggerWizard.sbr"
	-@erase "$(INTDIR)\units.obj"
	-@erase "$(INTDIR)\units.sbr"
	-@erase "$(INTDIR)\userDefined.obj"
	-@erase "$(INTDIR)\userDefined.sbr"
	-@erase "$(INTDIR)\userHelp.obj"
	-@erase "$(INTDIR)\userHelp.sbr"
	-@erase "$(INTDIR)\userMenu.obj"
	-@erase "$(INTDIR)\userMenu.sbr"
	-@erase "$(INTDIR)\vc60.idb"
	-@erase "$(INTDIR)\vc60.pdb"
	-@erase "$(INTDIR)\vegen.obj"
	-@erase "$(INTDIR)\vegen.sbr"
	-@erase "$(INTDIR)\Vex.obj"
	-@erase "$(INTDIR)\Vex.sbr"
	-@erase "$(INTDIR)\wueWizard.obj"
	-@erase "$(INTDIR)\wueWizard.sbr"
	-@erase "$(OUTDIR)\megatune.bsc"
	-@erase "$(OUTDIR)\megatune.exe"
	-@erase "$(OUTDIR)\megatune.ilk"
	-@erase "$(OUTDIR)\megatune.pdb"

"$(OUTDIR)" :
    if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

F90=df.exe
CPP=cl.exe
CPP_PROJ=/nologo /MDd /W3 /Gm /GR /GX /Zi /Od /D "WIN32" /D "_DEBUG" /D "_WINDOWS" /D "_AFXDLL" /FR"$(INTDIR)\\" /Fp"$(INTDIR)\megatune.pch" /Yu"stdafx.h" /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c 

.c{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.c{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

MTL=midl.exe
MTL_PROJ=/nologo /D "_DEBUG" /mktyplib203 /o "NUL" /win32 
RSC=rc.exe
RSC_PROJ=/l 0x409 /fo"$(INTDIR)\megatune.res" /d "_DEBUG" /d "_AFXDLL" 
BSC32=bscmake.exe
BSC32_FLAGS=/nologo /o"$(OUTDIR)\megatune.bsc" 
BSC32_SBRS= \
	"$(INTDIR)\aeWizard.sbr" \
	"$(INTDIR)\AnalogMeter.sbr" \
	"$(INTDIR)\Application.sbr" \
	"$(INTDIR)\BarMeter.sbr" \
	"$(INTDIR)\burstLog.sbr" \
	"$(INTDIR)\byteString.sbr" \
	"$(INTDIR)\COMSymbol.sbr" \
	"$(INTDIR)\controller.sbr" \
	"$(INTDIR)\curveEditor.sbr" \
	"$(INTDIR)\Dabout.sbr" \
	"$(INTDIR)\dataDialog.sbr" \
	"$(INTDIR)\datalog.sbr" \
	"$(INTDIR)\Dconplot.sbr" \
	"$(INTDIR)\Dconstants.sbr" \
	"$(INTDIR)\Denrichments.sbr" \
	"$(INTDIR)\dirSelect.sbr" \
	"$(INTDIR)\DlogOptions.sbr" \
	"$(INTDIR)\Dreqfuel.sbr" \
	"$(INTDIR)\Druntime.sbr" \
	"$(INTDIR)\Dsetcomm.sbr" \
	"$(INTDIR)\tuning3D.sbr" \
	"$(INTDIR)\DveGen.sbr" \
	"$(INTDIR)\gaugeConfig.sbr" \
	"$(INTDIR)\genO2.sbr" \
	"$(INTDIR)\genTherm.sbr" \
	"$(INTDIR)\hexedit.sbr" \
	"$(INTDIR)\injControl.sbr" \
	"$(INTDIR)\injectorSize.sbr" \
	"$(INTDIR)\megatune.sbr" \
	"$(INTDIR)\megatuneDlg.sbr" \
	"$(INTDIR)\miniDOM.sbr" \
	"$(INTDIR)\miniTerm.sbr" \
	"$(INTDIR)\msComm.sbr" \
	"$(INTDIR)\msDatabase.sbr" \
	"$(INTDIR)\msqInfoDlg.sbr" \
	"$(INTDIR)\parser.sbr" \
	"$(INTDIR)\plot3d.sbr" \
	"$(INTDIR)\portEdit.sbr" \
	"$(INTDIR)\repository.sbr" \
	"$(INTDIR)\scaleVe.sbr" \
	"$(INTDIR)\selectList.sbr" \
	"$(INTDIR)\Splash.sbr" \
	"$(INTDIR)\StdAfx.sbr" \
	"$(INTDIR)\symbol.sbr" \
	"$(INTDIR)\tableEditor.sbr" \
	"$(INTDIR)\tokenizer.sbr" \
	"$(INTDIR)\tpgen.sbr" \
	"$(INTDIR)\transformTable.sbr" \
	"$(INTDIR)\triggerWizard.sbr" \
	"$(INTDIR)\units.sbr" \
	"$(INTDIR)\userDefined.sbr" \
	"$(INTDIR)\userHelp.sbr" \
	"$(INTDIR)\userMenu.sbr" \
	"$(INTDIR)\vegen.sbr" \
	"$(INTDIR)\Vex.sbr" \
	"$(INTDIR)\wueWizard.sbr"

"$(OUTDIR)\megatune.bsc" : "$(OUTDIR)" $(BSC32_SBRS)
    $(BSC32) @<<
  $(BSC32_FLAGS) $(BSC32_SBRS)
<<

LINK32=link.exe
LINK32_FLAGS=winmm.lib /nologo /subsystem:windows /incremental:yes /pdb:"$(OUTDIR)\megatune.pdb" /debug /machine:I386 /out:"$(OUTDIR)\megatune.exe" /pdbtype:sept 
LINK32_OBJS= \
	"$(INTDIR)\aeWizard.obj" \
	"$(INTDIR)\AnalogMeter.obj" \
	"$(INTDIR)\Application.obj" \
	"$(INTDIR)\BarMeter.obj" \
	"$(INTDIR)\burstLog.obj" \
	"$(INTDIR)\byteString.obj" \
	"$(INTDIR)\COMSymbol.obj" \
	"$(INTDIR)\controller.obj" \
	"$(INTDIR)\curveEditor.obj" \
	"$(INTDIR)\Dabout.obj" \
	"$(INTDIR)\dataDialog.obj" \
	"$(INTDIR)\datalog.obj" \
	"$(INTDIR)\Dconplot.obj" \
	"$(INTDIR)\Dconstants.obj" \
	"$(INTDIR)\Denrichments.obj" \
	"$(INTDIR)\dirSelect.obj" \
	"$(INTDIR)\DlogOptions.obj" \
	"$(INTDIR)\Dreqfuel.obj" \
	"$(INTDIR)\Druntime.obj" \
	"$(INTDIR)\Dsetcomm.obj" \
	"$(INTDIR)\tuning3D.obj" \
	"$(INTDIR)\DveGen.obj" \
	"$(INTDIR)\gaugeConfig.obj" \
	"$(INTDIR)\genO2.obj" \
	"$(INTDIR)\genTherm.obj" \
	"$(INTDIR)\hexedit.obj" \
	"$(INTDIR)\injControl.obj" \
	"$(INTDIR)\injectorSize.obj" \
	"$(INTDIR)\megatune.obj" \
	"$(INTDIR)\megatuneDlg.obj" \
	"$(INTDIR)\miniDOM.obj" \
	"$(INTDIR)\miniTerm.obj" \
	"$(INTDIR)\msComm.obj" \
	"$(INTDIR)\msDatabase.obj" \
	"$(INTDIR)\msqInfoDlg.obj" \
	"$(INTDIR)\parser.obj" \
	"$(INTDIR)\plot3d.obj" \
	"$(INTDIR)\portEdit.obj" \
	"$(INTDIR)\repository.obj" \
	"$(INTDIR)\scaleVe.obj" \
	"$(INTDIR)\selectList.obj" \
	"$(INTDIR)\Splash.obj" \
	"$(INTDIR)\StdAfx.obj" \
	"$(INTDIR)\symbol.obj" \
	"$(INTDIR)\tableEditor.obj" \
	"$(INTDIR)\tokenizer.obj" \
	"$(INTDIR)\tpgen.obj" \
	"$(INTDIR)\transformTable.obj" \
	"$(INTDIR)\triggerWizard.obj" \
	"$(INTDIR)\units.obj" \
	"$(INTDIR)\userDefined.obj" \
	"$(INTDIR)\userHelp.obj" \
	"$(INTDIR)\userMenu.obj" \
	"$(INTDIR)\vegen.obj" \
	"$(INTDIR)\Vex.obj" \
	"$(INTDIR)\wueWizard.obj" \
	"$(INTDIR)\megatune.res"

"$(OUTDIR)\megatune.exe" : "$(OUTDIR)" $(DEF_FILE) $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

!ENDIF 


!IF "$(NO_EXTERNAL_DEPS)" != "1"
!IF EXISTS("megatune.dep")
!INCLUDE "megatune.dep"
!ELSE 
!MESSAGE Warning: cannot find "megatune.dep"
!ENDIF 
!ENDIF 


!IF "$(CFG)" == "megatune - Win32 Release" || "$(CFG)" == "megatune - Win32 Debug"
SOURCE=.\aeWizard.cpp

"$(INTDIR)\aeWizard.obj"	"$(INTDIR)\aeWizard.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\AnalogMeter.cpp

"$(INTDIR)\AnalogMeter.obj"	"$(INTDIR)\AnalogMeter.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Application.cpp

"$(INTDIR)\Application.obj"	"$(INTDIR)\Application.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\BarMeter.cpp

"$(INTDIR)\BarMeter.obj"	"$(INTDIR)\BarMeter.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\burstLog.cpp

"$(INTDIR)\burstLog.obj"	"$(INTDIR)\burstLog.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\byteString.cxx

"$(INTDIR)\byteString.obj"	"$(INTDIR)\byteString.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\COMSymbol.cpp

"$(INTDIR)\COMSymbol.obj"	"$(INTDIR)\COMSymbol.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\controller.cpp

"$(INTDIR)\controller.obj"	"$(INTDIR)\controller.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\curveEditor.cpp

"$(INTDIR)\curveEditor.obj"	"$(INTDIR)\curveEditor.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Dabout.cpp

"$(INTDIR)\Dabout.obj"	"$(INTDIR)\Dabout.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\dataDialog.cpp

"$(INTDIR)\dataDialog.obj"	"$(INTDIR)\dataDialog.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\datalog.cxx

"$(INTDIR)\datalog.obj"	"$(INTDIR)\datalog.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Dconplot.cpp

"$(INTDIR)\Dconplot.obj"	"$(INTDIR)\Dconplot.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Dconstants.cpp

"$(INTDIR)\Dconstants.obj"	"$(INTDIR)\Dconstants.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Denrichments.cpp

"$(INTDIR)\Denrichments.obj"	"$(INTDIR)\Denrichments.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\dirSelect.cxx

"$(INTDIR)\dirSelect.obj"	"$(INTDIR)\dirSelect.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\DlogOptions.cpp

"$(INTDIR)\DlogOptions.obj"	"$(INTDIR)\DlogOptions.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Dreqfuel.cpp

"$(INTDIR)\Dreqfuel.obj"	"$(INTDIR)\Dreqfuel.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Druntime.cpp

"$(INTDIR)\Druntime.obj"	"$(INTDIR)\Druntime.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Dsetcomm.cpp

"$(INTDIR)\Dsetcomm.obj"	"$(INTDIR)\Dsetcomm.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\tuning3D.cpp

"$(INTDIR)\tuning3D.obj"	"$(INTDIR)\tuning3D.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\DveGen.cpp

"$(INTDIR)\DveGen.obj"	"$(INTDIR)\DveGen.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\gaugeConfig.cpp

"$(INTDIR)\gaugeConfig.obj"	"$(INTDIR)\gaugeConfig.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\genO2.cpp

"$(INTDIR)\genO2.obj"	"$(INTDIR)\genO2.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\genTherm.cpp

"$(INTDIR)\genTherm.obj"	"$(INTDIR)\genTherm.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\hexedit.cpp

"$(INTDIR)\hexedit.obj"	"$(INTDIR)\hexedit.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\injControl.cpp

"$(INTDIR)\injControl.obj"	"$(INTDIR)\injControl.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\injectorSize.cpp

"$(INTDIR)\injectorSize.obj"	"$(INTDIR)\injectorSize.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\megatune.cpp

"$(INTDIR)\megatune.obj"	"$(INTDIR)\megatune.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Megatune.idl

!IF  "$(CFG)" == "megatune - Win32 Release"

MTL_SWITCHES=/nologo /D "NDEBUG" /tlb "$(OUTDIR)\Megatune.tlb" /h "Megatune_i.h" /iid "Megatune_i.c" /Oicf /o "NUL" /win32 

"$(INTDIR)\Megatune.tlb"	".\Megatune_i.h"	".\Megatune_i.c" : $(SOURCE) "$(INTDIR)"
	$(MTL) @<<
  $(MTL_SWITCHES) $(SOURCE)
<<


!ELSEIF  "$(CFG)" == "megatune - Win32 Debug"

MTL_SWITCHES=/nologo /D "_DEBUG" /tlb "$(OUTDIR)\Megatune.tlb" /h "Megatune_i.h" /iid "Megatune_i.c" /Oicf /o "NUL" /win32 

"$(INTDIR)\Megatune.tlb"	".\Megatune_i.h"	".\Megatune_i.c" : $(SOURCE) "$(INTDIR)"
	$(MTL) @<<
  $(MTL_SWITCHES) $(SOURCE)
<<


!ENDIF 

SOURCE=.\megatune.rc

"$(INTDIR)\megatune.res" : $(SOURCE) "$(INTDIR)"
	$(RSC) $(RSC_PROJ) $(SOURCE)


SOURCE=.\megatuneDlg.cpp

"$(INTDIR)\megatuneDlg.obj"	"$(INTDIR)\megatuneDlg.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\miniDOM.cpp

"$(INTDIR)\miniDOM.obj"	"$(INTDIR)\miniDOM.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\miniTerm.cpp

"$(INTDIR)\miniTerm.obj"	"$(INTDIR)\miniTerm.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\msComm.cpp

"$(INTDIR)\msComm.obj"	"$(INTDIR)\msComm.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\msDatabase.cpp

"$(INTDIR)\msDatabase.obj"	"$(INTDIR)\msDatabase.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\msqInfoDlg.cpp

"$(INTDIR)\msqInfoDlg.obj"	"$(INTDIR)\msqInfoDlg.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\parser.cxx

"$(INTDIR)\parser.obj"	"$(INTDIR)\parser.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\plot3d.cpp

"$(INTDIR)\plot3d.obj"	"$(INTDIR)\plot3d.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\portEdit.cpp

"$(INTDIR)\portEdit.obj"	"$(INTDIR)\portEdit.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\repository.cpp

"$(INTDIR)\repository.obj"	"$(INTDIR)\repository.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\scaleVe.cpp

"$(INTDIR)\scaleVe.obj"	"$(INTDIR)\scaleVe.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\selectList.cpp

"$(INTDIR)\selectList.obj"	"$(INTDIR)\selectList.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Splash.cpp

"$(INTDIR)\Splash.obj"	"$(INTDIR)\Splash.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\StdAfx.cpp

!IF  "$(CFG)" == "megatune - Win32 Release"

CPP_SWITCHES=/nologo /MT /W3 /GR /GX /O2 /D "WIN32" /D "NDEBUG" /D "_WINDOWS" /FR"$(INTDIR)\\" /Fp"$(INTDIR)\megatune.pch" /Yc"stdafx.h" /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c 

"$(INTDIR)\StdAfx.obj"	"$(INTDIR)\StdAfx.sbr"	"$(INTDIR)\megatune.pch" : $(SOURCE) "$(INTDIR)"
	$(CPP) @<<
  $(CPP_SWITCHES) $(SOURCE)
<<


!ELSEIF  "$(CFG)" == "megatune - Win32 Debug"

CPP_SWITCHES=/nologo /MDd /W3 /Gm /GR /GX /Zi /Od /D "WIN32" /D "_DEBUG" /D "_WINDOWS" /D "_AFXDLL" /FR"$(INTDIR)\\" /Fp"$(INTDIR)\megatune.pch" /Yc"stdafx.h" /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c 

"$(INTDIR)\StdAfx.obj"	"$(INTDIR)\StdAfx.sbr"	"$(INTDIR)\megatune.pch" : $(SOURCE) "$(INTDIR)"
	$(CPP) @<<
  $(CPP_SWITCHES) $(SOURCE)
<<


!ENDIF 

SOURCE=.\symbol.cpp

"$(INTDIR)\symbol.obj"	"$(INTDIR)\symbol.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\tableEditor.cpp

"$(INTDIR)\tableEditor.obj"	"$(INTDIR)\tableEditor.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\tokenizer.cpp

"$(INTDIR)\tokenizer.obj"	"$(INTDIR)\tokenizer.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\tpgen.cpp

"$(INTDIR)\tpgen.obj"	"$(INTDIR)\tpgen.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\transformTable.cpp

"$(INTDIR)\transformTable.obj"	"$(INTDIR)\transformTable.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\triggerWizard.cpp

"$(INTDIR)\triggerWizard.obj"	"$(INTDIR)\triggerWizard.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\units.cpp

"$(INTDIR)\units.obj"	"$(INTDIR)\units.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\userDefined.cpp

"$(INTDIR)\userDefined.obj"	"$(INTDIR)\userDefined.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\userHelp.cpp

"$(INTDIR)\userHelp.obj"	"$(INTDIR)\userHelp.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\userMenu.cpp

"$(INTDIR)\userMenu.obj"	"$(INTDIR)\userMenu.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\vegen.cxx

"$(INTDIR)\vegen.obj"	"$(INTDIR)\vegen.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\Vex.cpp

"$(INTDIR)\Vex.obj"	"$(INTDIR)\Vex.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"


SOURCE=.\wueWizard.cpp

"$(INTDIR)\wueWizard.obj"	"$(INTDIR)\wueWizard.sbr" : $(SOURCE) "$(INTDIR)" "$(INTDIR)\megatune.pch"



!ENDIF 

