//------------------------------------------------------------------------------
//--  Copyright (c) 2003,2004,2005,2006 by Eric Fahlgren                      --
//--  All Rights Reserved.                                                    --
//--                                                                          --
//--  This program is free software; you can redistribute it and/or           --
//--  modify it under the terms of the GNU General Public License             --
//--  as published by the Free Software Foundation; either version            --
//--  2 of the License, or (at your option) any later version.                --
//--  See http://www.gnu.org/licenses/gpl.txt                                 --
//------------------------------------------------------------------------------

#ifndef STRINGCONSTANTS_H
#define STRINGCONSTANTS_H 1

//------------------------------------------------------------------------------

#define S_accCorrBar                "accCorrBar"
#define S_airdenCorrBar             "airdenCorrBar"
#define S_alertColor                "alertColor"
#define S_allowAutoTune             "allowAutoTune"
#define S_array                     "array"
#define S_array1D                   "array1D"
#define S_array2D                   "array2D"
#define S_backgroundColor           "backgroundColor"
#define S_barHysteresis             "barHysteresis"
#define S_baroCorrBar               "baroCorrBar"
#define S_batteryBar                "batteryBar"
#define S_batteryVoltage            "batteryVoltage"
#define S_bgDangerColor             "bgDangerColor"
#define S_bgWarningColor            "bgWarningColor"
#define S_bits                      "bits"
#define S_blockReadTimeout          "blockReadTimeout"
#define S_burnCommand               "burnCommand"
#define S_columnLabel               "columnLabel"
#define S_commPort                  "commPort"
#define S_commRate                  "commRate"
#define S_connected                 "connected"
#define S_coolant                   "coolant"
#define S_coolantBar                "coolantBar"
#define S_corrector                 "corrector"
#define S_cursorColor               "cursorColor"
#define S_cursorDepth               "cursorDepth"
#define S_cursorText                "cursorText"
#define S_curve                     "curve"
#define S_defaultExtension          "defaultExtension"
#define S_delimiter                 "delimiter"
#define S_dialog                    "dialog"
#define S_dutyCycleBar              "dutyCycleBar"
#define S_egoBar                    "egoBar"
#define S_egoCorrBar                "egoCorrBar"
#define S_egoLEDs                   "egoLEDs"
#define S_egoVoltage                "egoVoltage"
#define S_enableWrite               "enableWrite"
#define S_endianness                "endianness"
#define S_engine                    "engine"
#define S_entry                     "entry"
#define S_faceColor                 "faceColor"
#define S_field                     "field"
#define S_fieldColoring             "fieldColoring"
#define S_font                      "font"
#define S_FrontPage                 "FrontPage"
#define S_gammaEBar                 "gammaEBar"
#define S_gauge                     "gauge"
#define S_gaugeColumns              "gaugeColumns"
#define S_GaugeConfigurations       "GaugeConfigurations"
#define S_getCommand                "getCommand"
#define S_gridColor                 "gridColor"
#define S_gridHeight                "gridHeight"
#define S_gridOrient                "gridOrient"
#define S_help                      "help"
#define S_indicator                 "indicator"
#define S_initialDeltaT             "initialDeltaT"
#define S_initialStartupInterval    "initialStartupInterval"
#define S_interWriteDelay           "interWriteDelay"
#define S_ledAlertColor             "ledAlertColor"
#define S_ledColor                  "ledColor"
#define S_logging                   "logging"
#define S_lumpiness                 "lumpiness"
#define S_mapBar                    "mapBar"
#define S_mapDotBar                 "mapDotBar"
#define S_markOnTrue                "markOnTrue"
#define S_matBar                    "matBar"
#define S_menu                      "menu"
#define S_menuDialog                "menuDialog"
#define S_MTversion                 "MTversion"
#define S_needleColor               "needleColor"
#define S_nPages                    "nPages"
#define S_ochBlockSize              "ochBlockSize"
#define S_ochGetCommand             "ochGetCommand"
#define S_on                        "on"
#define S_page                      "page"
#define S_pageActivate              "pageActivate"
#define S_pageActivationDelay       "pageActivationDelay"
#define S_pageButtons               "pageButtons"
#define S_pageChunkRead             "pageChunkRead"
#define S_pageChunkWrite            "pageChunkWrite"
#define S_pageIdentifier            "pageIdentifier"
#define S_pageReadCommand           "pageReadCommand"
#define S_pageSize                  "pageSize"
#define S_pageValueRead             "pageValueRead"
#define S_pageValueWrite            "pageValueWrite"
#define S_pageWriteCommand          "pageWriteCommand"
#define S_pct                       "%"
#define S_plugIn                    "plugIn"
#define S_pollingPattern            "pollingPattern"
#define S_proportionalGain          "proportionalGain"
#define S_pulseWidthBar             "pulseWidthBar"
#define S_queryCommand              "queryCommand"
#define S_rangeColor                "rangeColor"
#define S_raw                       "raw"
#define S_readonly                  "readonly"
#define S_restart                   "restart"
#define S_rpmBar                    "rpmBar"
#define S_saved                     "saved"
#define S_scalar                    "scalar"
#define S_scaleColor                "scaleColor"
#define S_secl                      "secl"
#define S_signature                 "signature"
#define S_spotColor                 "spotColor"
#define S_spotDepth                 "spotDepth"
#define S_spotText                  "spotText"
#define S_subMenu                   "subMenu"
#define S_table                     "table"
#define S_temperature               "temperature"
#define S_TEMPfmt                   "%TEMP"
#define S_tempTable                 "tempTable"
#define S_text                      "text"
#define S_textColor                 "textColor"
#define S_throttleBar               "throttleBar"
#define S_titleColor                "titleColor"
#define S_topicHelp                 "topicHelp"
#define S_TPS                       "TPS"
#define S_tpsADC                    "tpsADC"
#define S_tpsDotBar                 "tpsDotBar"
#define S_TPSfmt                    "%" S_TPS
#define S_true                      "true"
#define S_Tuning                    "Tuning"
#define S_UNDEFINED                 "UNDEFINED"
#define S_updateInterval            "updateInterval"
#define S_upDownLabel               "upDownLabel"
#define S_valueColor                "valueColor"
#define S_veBar                     "veBar"
#define S_veCorrBar                 "veCorrBar"
#define S_verify                    "verify"
#define S_versionInfo               "versionInfo"
#define S_veTuneLodIdx              "veTuneLodIdx"
#define S_veTuneRpmIdx              "veTuneRpmIdx"
#define S_veTuneValue               "veTuneValue"
#define S_warmupCorrBar             "warmupCorrBar"
#define S_warmupEnrich              "warmupEnrich"
#define S_webHelp                   "webHelp"
#define S_writeBlocks               "writeBlocks"
#define S_writeXML                  "writeXML"
#define S_xAxis                     "xAxis"
#define S_xBins                     "xBins"
#define S_xLimits                   "xLimits"
#define S_xRadius                   "xRadius"
#define S_yAxis                     "yAxis"
#define S_yBins                     "yBins"
#define S_yLimits                   "yLimits"
#define S_yRadius                   "yRadius"
#define S_zBins                     "zBins"
#define S_zLimits                   "zLimits"

#define S__AccelerationWizard_      "[AccelerationWizard]"
#define S__AutoTune_                "[AutoTune]"
#define S__BurstMode_               "[BurstMode]"
#define S__ColorMap_                "[ColorMap]"
#define S__Constants_               "[Constants]"
#define S__CurveEditor_             "[CurveEditor]"
#define S__Datalog_                 "[Datalog]"
#define S__Defaults_                "[Defaults]"
#define S__FrontPage_               "[FrontPage]"
#define S__GaugeColors_             "[GaugeColors]"
#define S__GaugeConfigurations_     "[GaugeConfigurations]"
#define S__MegaTune_                "[MegaTune]"
#define S__Menu_                    "[Menu]"
#define S__OutputChannels_          "[OutputChannels]"
#define S__RunTime_                 "[RunTime]"
#define S__TableEditor_             "[TableEditor]"
#define S__Tuning_                  "[Tuning]"
#define S__Units_                   "[Units]"
#define S__UserDefined_             "[UserDefined]"

//------------------------------------------------------------------------------
//--  Define the constants names used in the std_X dialog boxes.  --------------

#define S_aeEndPW                   "aeEndPW"
#define S_aeTaperTime               "aeTaperTime"
#define S_algorithm                 "algorithm"
#define S_alternate                 "alternate"
#define S_aseCount                  "aseCount"
#define S_asePct                    "asePct"
#define S_baroCorr                  "baroCorr"
#define S_battFac                   "battFac"
#define S_crankCold                 "crankCold"
#define S_crankHot                  "crankHot"
#define S_divider                   "divider"
#define S_egoCount                  "egoCount"
#define S_egoDelta                  "egoDelta"
#define S_egoLimit                  "egoLimit"
#define S_egoRPM                    "egoRPM"
#define S_egoSwitch                 "egoSwitch"
#define S_egoTemp                   "egoTemp"
#define S_egoType                   "egoType"
#define S_engineType                "engineType"
#define S_fastIdleT                 "fastIdleT"
#define S_floodClear                "floodClear"
#define S_injOpen                   "injOpen"
#define S_injPwmP                   "injPwmP"
#define S_injPwmT                   "injPwmT"
#define S_injType                   "injType"
#define S_maeBins                   "maeBins"
#define S_maeRates                  "maeRates"
#define S_mapDOT                    "mapDOT"
#define S_mapProportion             "mapProportion"
#define S_mapThresh                 "mapThresh"
#define S_mapType                   "mapType"
#define S_nCylinders                "nCylinders"
#define S_nInjectors                "nInjectors"
#define S_primePulse                "primePulse"
#define S_reqFuel                   "reqFuel"
#define S_rpmk                      "rpmk"
#define S_taeBins                   "taeBins"
#define S_taeColdA                  "taeColdA"
#define S_taeColdM                  "taeColdM"
#define S_taeRates                  "taeRates"
#define S_taeTime                   "taeTime"
#define S_tdePct                    "tdePct"
#define S_tpsDOT                    "tpsDOT"
#define S_tpsProportion             "tpsProportion"
#define S_tpsThresh                 "tpsThresh"
#define S_twoStroke                 "twoStroke"
#define S_wueBins                   "wueBins"

//------------------------------------------------------------------------------
//--  Variables used only in the run-time dialog.  Remove someday.  ------------

#define S_accelEnrich               "accelEnrich"
#define S_airCorrection             "airCorrection"
#define S_baroCorrection            "baroCorrection"
#define S_barometer                 "barometer"
#define S_egoCorrection             "egoCorrection"
#define S_gammaEnrich               "gammaEnrich"
#define S_idleDC                    "idleDC"
#define S_map                       "map"
#define S_mat                       "mat"
#define S_pulseWidth                "pulseWidth"
#define S_rpm                       "rpm"
#define S_throttle                  "throttle"
#define S_veCurr                    "veCurr"

//------------------------------------------------------------------------------
#endif
